apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rootapp
  namespace: argocd
spec:
  destination:
    name: hub-control-plane
    namespace: argocd
  source:
    path: child-apps
    repoURL: 'https://github.com/VINEETHJK/dev-appofapps.git'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
