apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telemetry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: spoke-dev
  project: default
  source:
    path: prometheus_grafana
    repoURL: https://github.com/VINEETHJK/dev-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
